controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

create:
    path: /create
    controller: App\Controller\TutorialController::createAction

formulario:
    path: /formulario
    controller: App\Controller\ControllerBiblioCode::verFormulario

index:
    path: /
    controller: App\Controller\ControllerBiblioCode::verIndex