controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

create:
    path: /create
    controller: App\Controller\TutorialController::createAction

formulario:
    path: /formulario
    controller: App\Controller\ComunidadController::verComunidad

comunidad:
    path: /verComunidad
    controller: App\Controller\ComunidadController::verComunidad

provincia:
    path: /verProvincia
    controller: App\Controller\ProvinciaController::verProvincia

index:
    path: /
    controller: App\Controller\ControllerBiblioCode::verIndex