controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

formulario:
    path: /formulario
    controller: App\Controller\ComunidadController::verComunidad

index:
    path: /
    controller: App\Controller\BiblioCodeController::verIndex

getTutorial:
    path: /api/tutorial/{id}
    controller: App\Controller\TutorialController::getTutorial
    methods: ["GET"]

getAllTutorial:
    path: /api/tutorial
    controller: App\Controller\TutorialController::getAllTutorial
    methods: ["GET"]

postTutorial:
    path: /api/tutorial
    controller: App\Controller\TutorialController::postTutorial
    methods: ["POST"]

putTutorial:
    path: /api/tutorial/{id}
    controller: App\Controller\TutorialController::putTutorial
    methods: ["PUT"]

deleteTutorial:
    path: /api/tutorial/{id}
    controller: App\Controller\TutorialController::deleteTutorial
    methods: ["DELETE"]

app_logout:
    path: /logout
    controller: App\Controller\TutorialController::logout