controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\BiblioCodeController::verIndex

formulario:
    path: /formulario
    controller: App\Controller\BiblioCodeController::verFormulario

grafica:
    path: /grafica
    controller: App\Controller\BiblioCodeController::verGraficaTutoriales

graficaDatosTitulo:
    path: /grafica/datos
    controller: App\Controller\BiblioCodeController::getAllDatosTitulo

graficaDatosLenguaje:
    path: /grafica/lenguaje
    controller: App\Controller\BiblioCodeController::getAllDatosLenguaje

tablaTutoriales:
    path: /tutoriales
    controller: App\Controller\BiblioCodeController::verTablaTutoriales

tutorialDatos:
    path: /api/tutorial/datos
    controller: App\Controller\TutorialController::getAllDatos

verTutorial:
    path: /tutorial/{id}
    controller: App\Controller\BiblioCodeController::verTutorial
    methods: ["GET"]

getTutorial:
    path: /api/tutorial/{id}
    controller: App\Controller\TutorialController::getTutorial
    methods: ["GET"]

getAllTutorial:
    path: /api/tutorial
    controller: App\Controller\TutorialController::getAllTutorial
    methods: ["GET"]

postTutorial:
    path: /api/tutorial
    controller: App\Controller\TutorialController::postTutorial
    methods: ["POST"]

putTutorial:
    path: /api/tutorial/{id}
    controller: App\Controller\TutorialController::putTutorial
    methods: ["PUT"]

deleteTutorial:
    path: /api/tutorial/{id}
    controller: App\Controller\TutorialController::deleteTutorial
    methods: ["DELETE"]

app_logout:
    path: /logout
    controller: App\Controller\TutorialController::logout